import { useState } from "react";
import { Menu, X, Home, Users, FileText, Activity, Clipboard } from "lucide-react";
import "./Analysis.css";

const Analysis = () => {
  const [isCollapsed, setIsCollapsed] = useState(false);

  const menuItems = [
    { name: "Dashboard", icon: <Home /> },
    { name: "Relationship Mapping", icon: <Users /> },
    { name: "Analysis", icon: <Activity /> },
    { name: "Citizen Record", icon: <Clipboard /> },
    { name: "Audit Log", icon: <FileText /> },
  ];

  return (
    <div className="dashboard-container">
      <aside className={`sidebar ${isCollapsed ? "collapsed" : ""}`}>
        <div className="sidebar-header">
          {!isCollapsed && <span>ARM Dashboard</span>}
          <button onClick={() => setIsCollapsed(!isCollapsed)} className="toggle-btn">
            {isCollapsed ? <Menu /> : <X />}
          </button>
        </div>
        <nav className="sidebar-nav">
          {menuItems.map((item) => (
            <a key={item.name} href="#">
              {item.icon} {!isCollapsed && item.name}
            </a>
          ))}
        </nav>
        <div className="sidebar-footer">
          {!isCollapsed && (
            <>
              <img src="https://via.placeholder.com/30" alt="User" className="user-avatar" />
              <span>Username</span>
            </>
          )}
        </div>
      </aside>

      <main className="main-content">
        <div className="content-header">
          <h1>Find Relationship</h1>
          <p>Quick Relationship Analyzer</p>
        </div>

        <div className="relation-form">
          <input type="text" placeholder="Enter CID of person A" className="input-box" />
          <button className="analyze-btn">Analyze</button>
          <input type="text" placeholder="Enter CID of person B" className="input-box" />
        </div>

        <section className="analysis-results">
          <div className="result-status">
            <strong>Analysis Complete</strong>
            <p>The AI has analyzed the relationship between person A and person B.</p>
          </div>

          <div className="result-box">
            <h3>Analysis Result</h3>
            <p>AI-generated insights about the relationship between the two citizens</p>

            <div className="result-details">
              <div>
                <strong>Relationship Type: </strong>
                <span>First Cousin</span>
              </div>
              <ul>
                <li>Both share a common grandfather CID.</li>
                <li>Their fathers (Person A and Person B) are brothers.</li>
                <li>Multiple family connections exist through extended family members.</li>
              </ul>
              <div className="accuracy">
                <span className="percentage">89%</span>
                <span>Accuracy percentage</span>
              </div>
              <div className="disclaimer">
                <strong>AI-Generated Content Disclaimer</strong>
                <p>
                  This analysis is generated by artificial intelligence and may not be 100% accurate.
                  Results should be verified through additional sources before making important decisions.
                </p>
              </div>
              <div className="actions">
                <button className="save-btn">Save</button>
                <button className="export-btn">Export</button>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
};

export default Analysis;
